theme: minima
title: Hey 
author: Deepika
email: your-deepikasanathanan12342gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal Blog

# social links
linkedin_username: Deepika S R # DO NOT include the @ character, or else the build will fail!
github_username:  DeepikaSR4  # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
